import puppeteer from 'puppeteer';
import { fileURLToPath } from 'url';
import path from 'path';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const browser = await puppeteer.launch({ headless: true });
const page = await browser.newPage();
await page.setViewport({ width: 512, height: 512 });
await page.goto(`file://${__dirname}/icon.html`, { waitUntil: 'networkidle0' });
await page.screenshot({ path: `${__dirname}/icon.png` });
await browser.close();
console.log('Done!');
